build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: mikkeloscar/maze-publish
    tag: latest
    storage_driver: overlay
    when:
      branch: master

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: mikkeloscar/maze-publish
    tag: develop
    storage_driver: overlay
    when:
      branch: develop
